<?php
define('Web_Url','yzm.zhzhxxyy.com'); //站点域名  
define('Web_Domain','yzm.zhzhxxyy.com'); //转码域名  
define('Web_Play',''); //m3u8域名  
define('Web_Path','/'); //站点路径  
define('Web_On',1); //是否开启前台，0关闭1开启  
define('Admin_Name','admin');  //后台用户名  
define('Admin_Code','admin');  //后台验证码  
define('Jpg_On',0);  //截图开关，0打开1关闭  
define('Jpg_Num',1);  //截图张数  
define('Jpg_Time',5);  //间隔秒数  
define('Jpg_Size','');  //截图尺寸  
define('Gif_On',0);  //动图开关，0打开1关闭  
define('Gif_Time',3);  //动图开始位置  
define('Gif_Len',3);  //动图时长  
define('Gif_Size','');  //动图尺寸  
define('Mu_On',1);  //加密开关，0加密1不加密  
define('Mq_On',1);  //秒切开关，0秒切1不秒切  
define('Mp_On',1);  //音频处理，0复制1不复制  
define('Mu_Time',5);  //每个TS的时长  
define('Mu_Type',0);  //多码率  
define('Mu_Kbps','1000k');  //转码码率  
define('Mu_Size','');  //缩放尺寸  
define('Mu_Kbps2','');  //转码码率2  
define('Mu_Size2','');  //缩放尺寸2  
define('Mu_Path','./video/m3u8/');  //保存路径  
define('Mu_Dir','');  //待转码目录  
define('Mu_Key','IkFH9WNyit1nzux0');  //加密密钥  
define('Mu_Tsext','');  //Ts伪装后缀  
define('Mu_PtTime',0);  //跳过片头秒数  
define('Mu_Ffpath','./packs/');  //ffmpeg安装路径
define('Mu_M3u8_Name','[年]/[月]/[日]/[md5]/index.m3u8');  //转码保存路径格式
define('Mu_Pic_Name','[年]/[月]/[日]/[md5]/vod.jpg'); //截图保存路径格式
define('Mu_Preset','medium'); //转码优先方式
define('Wm_On',0);  //左上水印开，0关闭1开启  
define('Wm_Lt','10:10');  //左上距离边界位置  
define('Wm_On2',0);  //右上水印开，0关闭1开启  
define('Wm_Lt2','10:10');  //右上距离边界位置  
define('Wm_On3',0);  //左下水印开，0关闭1开启  
define('Wm_Lt3','10:10');  //左下距离边界位置  
define('Wm_On4',0);  //右下水印开，0关闭1开启  
define('Wm_Lt4','10:10');  //右下距离边界位置  
define('Wm_Zm',0);  //是否启用字幕。0关闭，1启用  
define('Video_Path','./video/data/');  //上传文件保存路径（绝对路径）  
define('Video_SrcOn',1);  //保留原文件0保留1不保留  
define('Video_M3u8On',1);  //删除保留M3u8文件0保留1不保留  
define('Web_CrossDomain','');  //防盗链域名分号隔开  
define('Web_CrossOn',0);  //防盗链开关  
define('Web_Cross',1);  //防盗链直接播放开关  
define('Web_M3u8On',0);  //m3u8地址防盗开关  
define('Api_On',0);  //api同步开关0关闭1开启  
define('Api_Url','http://spf.zhzhxxyy.com/video');  //api同步地址  
define('Api_Key','133333_yunzhuanma');  //api同步秘钥
define('Up_Miao',0);  //秒传开关0关闭1开启
define('Up_Api',1);  //外部上传开关0关闭1开启
define('Up_Ext','avi|wmv|mpeg|mp4|mov|mkv|flv|f4v|m4v|rmvb|rm|mpg');  //支持的上传格式